import { requireOptionalNativeModule } from "expo";
export type AlarmKitBridge = {
  soundVolumeVersion?(): number;
  appBlockVersion?(): number;
  appBlockStatus?(): { authorized: boolean; activeUntil: number };
  requestAppBlockAccess?(): Promise<void>;
  chooseBlockedApps?(selection: string, group: string): Promise<{ selection: string; count: number } | null>;
  isSupported(): boolean;
  authorizationStatus(): string;
  requestAuthorization(): Promise<string>;
  prepareCustomSound(uri: string, id: string): Promise<string>;
  schedule(input: {
    id: string;
    alarmId: string;
    hour: number;
    minute: number;
    days: number[];
    label: string;
    soundName?: string;
    volume?: number;
    timestamp?: number;
    appBlockSelection?: string;
    appBlockMinutes?: number;
  }): Promise<void>;
  cancel(id: string): Promise<void>;
  stop(id: string): Promise<void>;
  consumePendingAlarm(): string | null;
  activeAlarm?(): string | null;
  beginAlarm?(alarmId: string): void;
  completeAlarm?(alarmId: string): void;
  addListener?(event: "onAlarmStateChange", listener: () => void): { remove(): void };
  getAlarms(): Promise<{ id: string; state: string }[]>;
};
export default requireOptionalNativeModule<AlarmKitBridge>("DaybreakAlarmKit");
