// Generated by scripts/prepare-audio.cjs.
export const soundCatalog = [
  {
    "id": "lofi",
    "name": "Lo-fi",
    "category": "Soft",
    "file": "lesiakower-lo-fi-alarm-clock-243766.mp3",
    "nativeFile": "daybreak_lofi.wav",
    "duration": 29,
    "nativeDuration": 29,
    "originalDuration": 59.95197278911564
  },
  {
    "id": "wake_up",
    "name": "Wake Up",
    "category": "Soft",
    "file": "freesound_community-wake-up-33353.mp3",
    "nativeFile": "daybreak_wake_up.wav",
    "duration": 20.5,
    "nativeDuration": 20.5,
    "originalDuration": 20.519954648526078
  },
  {
    "id": "classic_bell",
    "name": "Classic Bell",
    "category": "Classic",
    "file": "78562__joedeshon__alarm_clock_ringing_01.wav",
    "nativeFile": "daybreak_classic_bell.wav",
    "duration": 26.4,
    "nativeDuration": 26.4,
    "originalDuration": 26.435736961451248
  },
  {
    "id": "retro_clock",
    "name": "Retro Clock",
    "category": "Classic",
    "file": "freesound_community-alarm-clock-90867.mp3",
    "nativeFile": "daybreak_retro_clock.wav",
    "duration": 6.1,
    "nativeDuration": 6.1,
    "originalDuration": 6.12
  },
  {
    "id": "short_ring",
    "name": "Short Ring",
    "category": "Classic",
    "file": "freesound_community-alarm-clock-short-6402.mp3",
    "nativeFile": "daybreak_short_ring.wav",
    "duration": 8.6,
    "nativeDuration": 8.6,
    "originalDuration": 8.591972789115646
  },
  {
    "id": "digital_beep",
    "name": "Digital Beep",
    "category": "Digital",
    "file": "371292__iamgiorgio__b1_alarm.mp3",
    "nativeFile": "daybreak_digital_beep.wav",
    "duration": 5,
    "nativeDuration": 5,
    "originalDuration": 4.963265306122449
  },
  {
    "id": "pulse",
    "name": "Pulse",
    "category": "Digital",
    "file": "211132__martinbeltov__alarm-type-sound.wav",
    "nativeFile": "daybreak_pulse.wav",
    "duration": 29,
    "nativeDuration": 29,
    "originalDuration": 40.919773242630384
  },
  {
    "id": "bright_alarm",
    "name": "Bright Alarm",
    "category": "Digital",
    "file": "freesound_community-wake-up-alarm-68067.mp3",
    "nativeFile": "daybreak_bright_alarm.wav",
    "duration": 17.1,
    "nativeDuration": 17.1,
    "originalDuration": 17.057959183673468
  },
  {
    "id": "electronic",
    "name": "Electronic",
    "category": "Digital",
    "file": "u_inx5oo5fv3-alarm-327234.mp3",
    "nativeFile": "daybreak_electronic.wav",
    "duration": 7.1,
    "nativeDuration": 7.1,
    "originalDuration": 7.08
  },
  {
    "id": "steady_alarm",
    "name": "Steady Alarm",
    "category": "Digital",
    "file": "soundreality-alarm-471496.mp3",
    "nativeFile": "daybreak_steady_alarm.wav",
    "duration": 29,
    "nativeDuration": 29,
    "originalDuration": 29.903990929705216
  },
  {
    "id": "rooster",
    "name": "Rooster",
    "category": "Playful",
    "file": "freesound_community-brahma-rooster-89888.mp3",
    "nativeFile": "daybreak_rooster.wav",
    "duration": 3.8,
    "nativeDuration": 3.8,
    "originalDuration": 3.84
  },
  {
    "id": "funny_alarm",
    "name": "Funny Alarm",
    "category": "Playful",
    "file": "3dabrar-funny-alarm-317531.mp3",
    "nativeFile": "daybreak_funny_alarm.wav",
    "duration": 9.5,
    "nativeDuration": 9.5,
    "originalDuration": 9.503990929705216
  },
  {
    "id": "arcade",
    "name": "Arcade Alarm",
    "category": "Playful",
    "file": "8footdino_on_scratch-alarm-301729.mp3",
    "nativeFile": "daybreak_arcade.wav",
    "duration": 23,
    "nativeDuration": 23,
    "originalDuration": 22.961632653061226
  },
  {
    "id": "biohazard",
    "name": "Biohazard",
    "category": "Intense",
    "file": "dennish18-biohazard-alarm-143105.mp3",
    "nativeFile": "daybreak_biohazard.wav",
    "duration": 29,
    "nativeDuration": 29,
    "originalDuration": 49.99836734693878
  },
  {
    "id": "emergency",
    "name": "Emergency Alert",
    "category": "Intense",
    "file": "jeremayjimenez-greece-eas-alarm-451404.mp3",
    "nativeFile": "daybreak_emergency.wav",
    "duration": 10.1,
    "nativeDuration": 10.1,
    "originalDuration": 10.05596371882086
  },
  {
    "id": "adhan_alafasy_fajr",
    "name": "Mishary Alafasy · Fajr",
    "category": "Islamic",
    "file": "Y2Mate.is - Adhan Call to prayer _ Mishary Rashid Alafasy _ Fajr _ Maqam Hijaz .mp3",
    "fullPlayback": true,
    "nativeFile": "daybreak_adhan_alafasy_fajr.wav",
    "duration": 254.3,
    "nativeDuration": 29,
    "originalDuration": 254.27696145124716
  },
  {
    "id": "adhan",
    "name": "Adhan",
    "category": "Islamic",
    "file": "Y2Mate.is - Best Adhan in the world - Muslim Call to Prayer.mp3",
    "fullPlayback": true,
    "nativeFile": "daybreak_adhan.wav",
    "duration": 213.4,
    "nativeDuration": 29,
    "originalDuration": 213.42145124716552
  }
] as const;
